name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
  deploy:
    needs: [build]
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH to AWX
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.AWX_USERNAME }}
          host: ${{ secrets.AWX_HOST }}
          key: ${{ secrets.AWX_SSH_KEY }}
          script: |
            tower-cli job launch --job-template=54 -v
